export enum EquipmentsActions {
  ADD_EQUIPMENT = 'ADD_EQUIPMENT',
  DELETE_EQUIPMENT = 'DELETE_EQUIPMENT',
  GET_EQUIPMENT = 'GET_EQUIPMENT',
  GET_EQUIPMENT_TYPES = 'GET_EQUIPMENT_TYPES',
  GET_EQUIPMENTS = 'GET_EQUIPMENTS',
  REFRESH_EQUIPMENT = 'REFRESH_EQUIPMENT',
  UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT',
  UPDATE_EQUIPMENT_TYPE = 'UPDATE_EQUIPMENT_TYPE',
}

export enum EquipmentsGetters {
  EQUIPMENT = 'EQUIPMENT',
  EQUIPMENTS = 'EQUIPMENTS',
  EQUIPMENT_TYPES = 'EQUIPMENT_TYPES',
  LOADING = 'LOADING',
}

export enum EquipmentsMutation {
  ADD_EQUIPMENT = 'ADD_EQUIPMENT',
  REMOVE_EQUIPMENT = 'REMOVE_EQUIPMENT',
  SET_EQUIPMENTS = 'SET_EQUIPMENTS',
  SET_EQUIPMENT_TYPES = 'SET_EQUIPMENT_TYPES',
  SET_LOADING = 'SET_LOADING',
  UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT',
}
