HOST = 0.0.0.0
API_PORT = 5000
CLIENT_PORT = 3000

export FLASK_APP = $(PWD)/fittrackee_api/server.py
export APP_SETTINGS=fittrackee_api.config.DevelopmentConfig
export FLASK_ENV=development
export TEST_URL = http://$(HOST):$(CLIENT_PORT)
export REQUIREMENTS = $(PWD)/fittrackee_api/requirements.txt
export DATABASE_URL = postgres://fittrackee:fittrackee@$(HOST):5432/fittrackee
export DATABASE_TEST_URL = postgres://fittrackee:fittrackee@$(HOST):5432/fittrackee_test
export MIGRATIONS = $(PWD)/fittrackee_api/migrations
export PIPENV_VENV_IN_PROJECT=true

# Python env
PYTHON_VERSION ?= python
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
PIPENV = $(shell command -v pipenv 2> /dev/null)
FLASK = $(VENV)/bin/flask
PYTEST = $(VENV)/bin/py.test
GUNICORN = $(VENV)/bin/gunicorn
COV = $(VENV)/bin/python-codacy-coverage

# Node env
NODE_MODULES = $(PWD)/node_modules
NPM ?= yarn
