HOST = 0.0.0.0
API_PORT = 5000
CLIENT_PORT = 3000

export FLASK_APP = $(PWD)/fittrackee/__main__.py
export FLASK_ENV=development
export TEST_APP_URL = http://$(HOST):$(API_PORT)
export TEST_CLIENT_URL = http://$(HOST):$(CLIENT_PORT)
export MIGRATIONS = $(PWD)/fittrackee/migrations

# Python env
PYTHON_VERSION ?= python
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
POETRY = poetry
FLASK = $(VENV)/bin/flask
PYTEST = $(VENV)/bin/py.test -c pyproject.toml -W ignore::DeprecationWarning
GUNICORN = $(VENV)/bin/gunicorn
BLACK = $(VENV)/bin/black

# Node env
NODE_MODULES = $(PWD)/fittrackee_client/node_modules
NPM ?= yarn

#Sphinx Docs
SPHINXOPTS ?=
SPHINXBUILD ?= $(VENV)/bin/sphinx-build
SOURCEDIR = docsrc/source
BUILDDIR = docsrc/build
