HOST = 0.0.0.0
API_PORT = 5000
CLIENT_PORT = 3000

export REACT_APP_API_URL ?= http://$(HOST):$(API_PORT)/api/
export FLASK_APP ?= $(PWD)/mpwo_api/server.py
export TEST_URL ?= http://$(HOST):$(CLIENT_PORT)
export REQUIREMENTS ?= $(PWD)/mpwo_api/requirements.txt
export DATABASE_URL ?= postgres://mpwo:mpwo@$(HOST):5432/mpwo
export DATABASE_TEST_URL ?= postgres://mpwo:mpwo@$(HOST):5432/mpwo_test

# Python env
PYTHON_VERSION ?= python
VENV = $(PWD)/mpwo_api/venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask

# Node env
NODE_MODULES = $(PWD)/mpwo_client/node_modules
NPM ?= yarn --modules-folder  mpwo_client/node_modules/
