export enum WorkoutsActions {
  GET_CALENDAR_WORKOUTS = 'GET_CALENDAR_WORKOUTS',
  GET_USER_WORKOUTS = 'GET_USER_WORKOUTS',
}

export enum WorkoutsGetters {
  CALENDAR_WORKOUTS = 'CALENDAR_WORKOUTS',
  USER_WORKOUTS = 'USER_WORKOUTS',
}

export enum WorkoutsMutations {
  EMPTY_WORKOUTS = 'EMPTY_WORKOUTS',
  SET_CALENDAR_WORKOUTS = 'SET_CALENDAR_WORKOUTS',
  SET_USER_WORKOUTS = 'SET_USER_WORKOUTS',
}
