export enum WorkoutsActions {
  GET_CALENDAR_WORKOUTS = 'GET_CALENDAR_WORKOUTS',
  GET_USER_WORKOUTS = 'GET_USER_WORKOUTS',
  GET_WORKOUT_DATA = 'GET_WORKOUT_DATA',
}

export enum WorkoutsGetters {
  CALENDAR_WORKOUTS = 'CALENDAR_WORKOUTS',
  USER_WORKOUTS = 'USER_WORKOUTS',
  WORKOUT_DATA = 'WORKOUT_DATA',
}

export enum WorkoutsMutations {
  EMPTY_WORKOUTS = 'EMPTY_WORKOUTS',
  EMPTY_WORKOUT = 'EMPTY_WORKOUT',
  SET_CALENDAR_WORKOUTS = 'SET_CALENDAR_WORKOUTS',
  SET_USER_WORKOUTS = 'SET_USER_WORKOUTS',
  SET_WORKOUT = 'SET_WORKOUT',
  SET_WORKOUT_GPX = 'SET_WORKOUT_GPX',
  SET_WORKOUT_CHART_DATA = 'SET_WORKOUT_CHART_DATA',
  SET_WORKOUT_LOADING = 'SET_WORKOUT_LOADING',
}
