"""add workouts limit for global map

Revision ID: 0a2e2369b972
Revises: fed271354410
Create Date: 2025-09-17 16:56:55.920185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2e2369b972'
down_revision = 'fed271354410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_map_workouts_limit', sa.Integer(), server_default='10000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('global_map_workouts_limit')

    # ### end Alembic commands ###
