"""add pace to 'workouts' and 'workout_segments' tables

Revision ID: 3dbea67b5e3b
Revises: e63433a1d62e
Create Date: 2025-11-29 12:06:13.083883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbea67b5e3b'
down_revision = 'e63433a1d62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ave_pace', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('max_pace', sa.Interval(), nullable=True))

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ave_pace', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('max_pace', sa.Interval(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('max_pace')
        batch_op.drop_column('ave_pace')

    with op.batch_alter_table('workout_segments', schema=None) as batch_op:
        batch_op.drop_column('max_pace')
        batch_op.drop_column('ave_pace')

    # ### end Alembic commands ###
