"""add missing_elevations_processing to 'users' and 'workouts' tables

Revision ID: c59425f77851
Revises: e63433a1d62e
Create Date: 2025-11-09 19:09:16.579739

"""

from alembic import op
import sqlalchemy as sa

from fittrackee.constants import ELEVATIONS_PROCESSING

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c59425f77851"
down_revision = "e63433a1d62e"
branch_labels = None
depends_on = None


def upgrade():
    elevations_processing = postgresql.ENUM(
        *ELEVATIONS_PROCESSING, name="elevations_processing"
    )
    elevations_processing.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "missing_elevations_processing",
                elevations_processing,
                server_default="none",
                nullable=False,
            )
        )

    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "missing_elevations_processing",
                elevations_processing,
                server_default="none",
                nullable=False,
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_column("missing_elevations_processing")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("missing_elevations_processing")

    # ### end Alembic commands ###
