"""add media

Revision ID: c9d5209ffbcd
Revises: 84394acbebcf
Create Date: 2026-03-22 11:55:27.024018

"""
from alembic import op
import sqlalchemy as sa
from fittrackee.database import TZDateTime

# revision identifiers, used by Alembic.
revision = 'c9d5209ffbcd'
down_revision = '84394acbebcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid ()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('created_at', TZDateTime(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1500), server_default=sa.text("''"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_file_name'), ['file_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_media_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_workout_id'), ['workout_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibility_levels'), server_default='PRIVATE', nullable=False))

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibility_levels'), server_default='PRIVATE', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('media_visibility')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('media_visibility')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_workout_id'))
        batch_op.drop_index(batch_op.f('ix_media_user_id'))
        batch_op.drop_index(batch_op.f('ix_media_file_name'))
        batch_op.drop_index(batch_op.f('ix_media_created_at'))

    op.drop_table('media')
    # ### end Alembic commands ###
