"""update blacklisted_tokens table

Revision ID: 2e3a59ebbc59
Revises: 3d0c336b7a9e
Create Date: 2026-07-29 20:17:58.268365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3a59ebbc59'
down_revision = '3d0c336b7a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('ix_blacklisted_tokens_jti', ['jti'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('ix_blacklisted_tokens_jti', type_='unique')
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
