"""add sports visibility levels

Revision ID: 7296339c8bdf
Revises: 3d0c336b7a9e
Create Date: 2026-06-03 18:36:25.969287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7296339c8bdf'
down_revision = '3d0c336b7a9e'
branch_labels = None
depends_on = None


def upgrade():
    visibility_level = sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibility_levels')
    
    with op.batch_alter_table('users_sports_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workouts_visibility', visibility_level, server_default='PRIVATE', nullable=False))
        batch_op.add_column(sa.Column('analysis_visibility', visibility_level, server_default='PRIVATE', nullable=False))
        batch_op.add_column(sa.Column('map_visibility',visibility_level, server_default='PRIVATE', nullable=False))
        batch_op.add_column(sa.Column('media_visibility', visibility_level, server_default='PRIVATE', nullable=False))

    # update existing sport preferences
    users_helper = sa.Table(
        'users',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workouts_visibility', visibility_level, nullable=False),
        sa.Column('analysis_visibility', visibility_level, nullable=False),
        sa.Column('map_visibility', visibility_level, nullable=False),
        sa.Column('media_visibility', visibility_level, nullable=False),
    )
    connection = op.get_bind()
    for user in connection.execute(users_helper.select()):
        op.execute(f"""
            UPDATE users_sports_preferences
            SET workouts_visibility = '{user.workouts_visibility}',
                analysis_visibility = '{user.analysis_visibility}',
                map_visibility = '{user.map_visibility}',
                media_visibility = '{user.media_visibility}'
            WHERE users_sports_preferences.user_id = {user.id}
            """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_sports_preferences', schema=None) as batch_op:
        batch_op.drop_column('media_visibility')
        batch_op.drop_column('map_visibility')
        batch_op.drop_column('analysis_visibility')
        batch_op.drop_column('workouts_visibility')

    # ### end Alembic commands ###
