"""add sports visibility levels

Revision ID: 7296339c8bdf
Revises: 3d0c336b7a9e
Create Date: 2026-06-03 18:36:25.969287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7296339c8bdf'
down_revision = '3d0c336b7a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_sports_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workouts_visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibility_levels'), server_default='PRIVATE', nullable=False))
        batch_op.add_column(sa.Column('analysis_visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibility_levels'), server_default='PRIVATE', nullable=False))
        batch_op.add_column(sa.Column('map_visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibility_levels'), server_default='PRIVATE', nullable=False))
        batch_op.add_column(sa.Column('media_visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='visibility_levels'), server_default='PRIVATE', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_sports_preferences', schema=None) as batch_op:
        batch_op.drop_column('media_visibility')
        batch_op.drop_column('map_visibility')
        batch_op.drop_column('analysis_visibility')
        batch_op.drop_column('workouts_visibility')

    # ### end Alembic commands ###
