"""update user preferences and workouts tables

Revision ID: cbee82450dd3
Revises: 7296339c8bdf
Create Date: 2026-06-07 11:28:54.447877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbee82450dd3'
down_revision = '7296339c8bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_stats_from_file', sa.Boolean(), server_default='False', nullable=False))

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_stats_from_file', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_column('workout_stats_from_file')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('workout_stats_from_file')

    # ### end Alembic commands ###
