"""add tile providers to app_config

Revision ID: 85e262f5150d
Revises: e5f7a2c1d9b8
Create Date: 2026-08-20 20:40:40.899774

"""
import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '85e262f5150d'
down_revision = 'e5f7a2c1d9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tile_providers', sa.ARRAY(sa.String()), server_default=sa.text("CAST(ARRAY['osm'] AS VARCHAR[])"), nullable=False))
        batch_op.add_column(sa.Column('default_tile_provider', sa.String(length=25), server_default='osm', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_tile_provider', sa.String(length=25), server_default='osm', nullable=False))

    # ### end Alembic commands ###

    tile_server_url = os.environ.get("TILE_SERVER_URL", "")
    title_provider = "custom" if tile_server_url else "osm"

    app_config = table(
        "app_config",
        column("tile_providers", sa.ARRAY(sa.String())),
        column("default_tile_provider", sa.String(length=25)),
    )
    op.execute(
        app_config.update().values(
            {
                "tile_providers": [title_provider],
                "default_tile_provider": title_provider,
            }
        )
    )
    users = table(
        "users",
        column("default_tile_provider", sa.String(length=25)),
    )
    op.execute(
        users.update().values({"default_tile_provider": title_provider})
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_tile_provider')

    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('default_tile_provider')
        batch_op.drop_column('tile_providers')

    # ### end Alembic commands ###
