"""add tile_providers to app_config

Revision ID: 85e262f5150d
Revises: e5f7a2c1d9b8
Create Date: 2026-08-20 20:40:40.899774

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import table, column

from fittrackee.application.tile_servers import get_custom_tile_provider

# revision identifiers, used by Alembic.
revision = '85e262f5150d'
down_revision = 'e5f7a2c1d9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tile_providers', sa.ARRAY(sa.String()), server_default=sa.text('CAST(ARRAY[] AS VARCHAR[])'), nullable=False))

    # ### end Alembic commands ###

    app_config = table(
        "app_config",
        column("tile_providers", sa.ARRAY(sa.String())),
    )
    op.execute(
        app_config.update().values(
            {"tile_providers": get_custom_tile_provider()}
        )
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_column('tile_providers')

    # ### end Alembic commands ###
