export enum ReportsActions {
  EMPTY_REPORTS = 'EMPTY_REPORTS',
  GET_REPORTS = 'GET_REPORTS',
  SUBMIT_REPORT = 'SUBMIT_REPORT',
}

export enum ReportsGetters {
  REPORTS = 'REPORTS',
  REPORTS_PAGINATION = 'REPORTS_PAGINATION',
  REPORT_STATUS = 'REPORT_STATUS',
}

export enum ReportsMutations {
  SET_REPORTS = 'SET_REPORTS',
  SET_REPORT_STATUS = 'SET_REPORT_STATUS',
  SET_REPORTS_PAGINATION = 'SET_REPORTS_PAGINATION',
}
