class AdminActionAppealForbiddenException(Exception): ...


class AdminActionForbiddenException(Exception): ...


class InvalidAdminActionAppealException(Exception): ...


class InvalidAdminActionAppealUserException(Exception): ...


class InvalidAdminActionException(Exception): ...
