export enum OAuth2Actions {
  AUTHORIZE_CLIENT = 'AUTHORIZE_CLIENT',
  CREATE_CLIENT = 'CREATE_CLIENT',
  DELETE_CLIENT = 'DELETE_CLIENT',
  GET_CLIENTS = 'GET_CLIENTS',
  GET_CLIENT_BY_CLIENT_ID = 'GET_CLIENT_BY_CLIENT_ID',
  GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID',
  REVOKE_ALL_TOKENS = 'REVOKE_ALL_TOKENS',
}

export enum OAuth2Getters {
  CLIENT = 'CLIENT',
  CLIENTS = 'CLIENTS',
  CLIENTS_PAGINATION = 'CLIENTS_PAGINATION',
  REVOCATION_SUCCESSFUL = 'REVOCATION_SUCCESSFUL',
}

export enum OAuth2Mutations {
  EMPTY_CLIENT = 'EMPTY_CLIENT',
  SET_CLIENT = 'SET_CLIENT',
  SET_CLIENTS = 'SET_CLIENTS',
  SET_CLIENTS_PAGINATION = 'SET_CLIENTS_PAGINATION',
  SET_REVOCATION_SUCCESSFUL = 'SET_REVOCATION_SUCCESSFUL',
}
