export enum NotificationsActions {
  GET_UNREAD_STATUS = 'GET_UNREAD_STATUS',
  GET_NOTIFICATION_TYPES = 'GET_NOTIFICATION_TYPES',
  GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
  MARK_ALL_AS_READ = 'MARK_ALL_AS_READ',
  UPDATE_STATUS = 'UPDATE_STATUS',
}
export enum NotificationsGetters {
  NOTIFICATIONS = 'NOTIFICATIONS',
  PAGINATION = 'PAGINATION',
  UNREAD_STATUS = 'UNREAD_STATUS',
  TYPES = 'TYPES',
}
export enum NotificationsMutations {
  UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS',
  UPDATE_PAGINATION = 'UPDATE_PAGINATION',
  UPDATE_TYPES = 'UPDATE_TYPES',
  UPDATE_UNREAD_STATUS = 'UPDATE_UNREAD_STATUS',
  EMPTY_NOTIFICATIONS = 'EMPTY_NOTIFICATIONS',
}
