export enum NotificationsActions {
  GET_UNREAD_STATUS = 'GET_UNREAD_STATUS',
  GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
  UPDATE_STATUS = 'UPDATE_STATUS',
}
export enum NotificationsGetters {
  NOTIFICATIONS = 'NOTIFICATIONS',
  PAGINATION = 'PAGINATION',
  UNREAD_STATUS = 'UNREAD_STATUS',
}
export enum NotificationsMutations {
  UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS',
  UPDATE_PAGINATION = 'UPDATE_PAGINATION',
  UPDATE_UNREAD_STATUS = 'UPDATE_UNREAD_STATUS',
  EMPTY_NOTIFICATIONS = 'EMPTY_NOTIFICATIONS',
}
