export enum StatisticsActions {
  GET_USER_SPORT_STATS = 'GET_USER_SPORT_STATS',
  GET_USER_STATS = 'GET_USER_STATS',
}

export enum StatisticsGetters {
  USER_SPORT_STATS = 'USER_SPORT_STATS',
  USER_STATS = 'USER_STATS',
  STATS_LOADING = 'STATS_LOADING',
}

export enum StatisticsMutations {
  EMPTY_USER_SPORT_STATS = 'EMPTY_USER_SPORT_STATS',
  EMPTY_USER_STATS = 'EMPTY_USER_STATS',
  UPDATE_USER_SPORT_STATS = 'UPDATE_USER_SPORT_STATS',
  UPDATE_USER_STATS = 'UPDATE_USER_STATS',
  UPDATE_STATS_LOADING = 'UPDATE_STATS_LOADING',
}
