export enum UsersActions {
  GET_USERS = 'GET_USERS',
}

export enum UsersGetters {
  USERS = 'USERS',
  USERS_LOADING = 'USERS_LOADING',
  USERS_PAGINATION = 'USERS_PAGINATION',
}

export enum UsersMutations {
  UPDATE_USERS = 'UPDATE_USERS',
  UPDATE_USERS_LOADING = 'UPDATE_USERS_LOADING',
  UPDATE_USERS_PAGINATION = 'UPDATE_USERS_PAGINATION',
}
