export enum UsersActions {
  EMPTY_USER = 'EMPTY_USER',
  EMPTY_USERS = 'EMPTY_USERS',
  GET_USER = 'GET_USER',
  GET_USERS = 'GET_USERS',
  UPDATE_USER = 'UPDATE_USER',
}

export enum UsersGetters {
  USER = 'USER',
  USERS = 'USERS',
  USERS_LOADING = 'USERS_LOADING',
  USERS_PAGINATION = 'USERS_PAGINATION',
}

export enum UsersMutations {
  UPDATE_USER = 'UPDATE_USER',
  UPDATE_USER_IN_USERS = 'UPDATE_USER_IN_USERS',
  UPDATE_USERS = 'UPDATE_USERS',
  UPDATE_USERS_LOADING = 'UPDATE_USERS_LOADING',
  UPDATE_USERS_PAGINATION = 'UPDATE_USERS_PAGINATION',
}
