DROP DATABASE IF EXISTS mpwo;
DROP DATABASE IF EXISTS mpwo_test;
CREATE DATABASE mpwo;
CREATE DATABASE mpwo_test;
CREATE USER mpwo WITH PASSWORD 'mpwo';
GRANT ALL PRIVILEGES ON DATABASE mpwo TO mpwo;
GRANT ALL PRIVILEGES ON DATABASE mpwo_test TO mpwo;
