export enum RootActions {
  GET_APPLICATION_CONFIG = 'GET_APPLICATION_CONFIG',
}

export enum RootGetters {
  ERROR_MESSAGES = 'ERROR_MESSAGES',
  LANGUAGE = 'LANGUAGE',
}

export enum RootMutations {
  EMPTY_ERROR_MESSAGES = 'EMPTY_ERROR_MESSAGES',
  SET_ERROR_MESSAGES = 'SET_ERROR_MESSAGES',
  UPDATE_APPLICATION_CONFIG = 'UPDATE_APPLICATION_CONFIG',
  UPDATE_LANG = 'UPDATE_LANG',
}
