export enum UserActions {
  CHECK_AUTH_USER = 'CHECK_AUTH_USER',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  LOGIN_OR_REGISTER = 'LOGIN_OR_REGISTER',
  LOGOUT = 'LOGOUT',
  UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE',
}

export enum UserGetters {
  AUTH_TOKEN = 'AUTH_TOKEN',
  AUTH_USER_PROFILE = 'AUTH_USER_PROFILE',
  IS_AUTHENTICATED = 'IS_AUTHENTICATED',
  USER_LOADING = 'USER_LOADING',
}

export enum UserMutations {
  CLEAR_AUTH_USER_TOKEN = 'CLEAR_AUTH_USER_TOKEN',
  UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN',
  UPDATE_AUTH_USER_PROFILE = 'UPDATE_AUTH_USER_PROFILE',
  UPDATE_USER_LOADING = 'UPDATE_USER_LOADING',
}
