export enum UserActions {
  GET_USER_PROFILE = 'GET_USER_PROFILE',
  LOGIN_OR_REGISTER = 'LOGIN_OR_REGISTER',
}

export enum UserGetters {
  AUTH_TOKEN = 'AUTH_TOKEN',
  AUTH_USER_PROFILE = 'AUTH_USER_PROFILE',
  IS_AUTHENTICATED = 'IS_AUTHENTICATED',
}

export enum UserMutations {
  UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN',
  UPDATE_AUTH_USER_PROFILE = 'UPDATE_AUTH_USER_PROFILE',
}
