class InvalidReportException(Exception): ...


class InvalidReporterException(Exception): ...


class ReportNotFoundException(Exception): ...


class ReportCommentForbiddenException(Exception): ...


class ReportForbiddenException(Exception): ...
